# Generated by Django 5.2.16 on 2026-07-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('center_type', models.CharField(choices=[('hospital', 'Hôpital/Clinique'), ('police', 'Poste de police'), ('ngo', 'ONG'), ('social', 'Service social'), ('legal', 'Aide juridique'), ('psychological', 'Soutien psychologique'), ('shelter', "Centre d'hébergement")], max_length=20)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('services_offered', models.TextField(help_text='Liste des services offerts')),
                ('opening_hours', models.CharField(max_length=200)),
                ('is_free', models.BooleanField(default=True)),
                ('accepts_anonymous', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Centre d'aide",
                'verbose_name_plural': "Centres d'aide",
                'db_table': 'support_centers',
                'ordering': ['name'],
            },
        ),
    ]
