from django.core.management.base import BaseCommand
from apps.centers.models import SupportCenter


CENTERS = [
    {
        "name": "CHU de Ouagadougou",
        "center_type": "hospital",
        "description": "Centre Hospitalier Universitaire de Ouagadougou, principal hopital du pays.",
        "address": "Chapelle, Ouagadougou",
        "city": "Ouagadougou",
        "province": "Centre",
        "phone": "+226 25 30 67 00",
        "email": "chu@ouaga.bf",
        "latitude": 12.3714,
        "longitude": -1.5197,
        "services_offered": "Urgences, maternite, pediatrie, chirurgie, gynecologie",
        "opening_hours": "24h/24",
        "is_free": True,
        "accepts_anonymous": True,
    },
    {
        "name": "CHU Yalgado Ouedraogo",
        "center_type": "hospital",
        "description": "Centre Hospitalier Universitaire Yalgado Ouedraogo.",
        "address": "Boulevard de la Revolution, Ouagadougou",
        "city": "Ouagadougou",
        "province": "Centre",
        "phone": "+226 25 33 72 47",
        "email": "chy@ouaga.bf",
        "latitude": 12.3693,
        "longitude": -1.5250,
        "services_offered": "Urgences, soins aux victimes de violence, gynecologie, psychiatrie",
        "opening_hours": "24h/24",
        "is_free": True,
        "accepts_anonymous": True,
    },
    {
        "name": "Hopital de Koudougou",
        "center_type": "hospital",
        "description": "Hopital regional de Koudougou.",
        "address": "Zone du sanatorium, Koudougou",
        "city": "Koudougou",
        "province": "Centre-Ouest",
        "phone": "+226 26 44 01 73",
        "email": "hopital@koudougou.bf",
        "latitude": 12.2537,
        "longitude": -2.3622,
        "services_offered": "Urgences, maternite, soins aux victimes",
        "opening_hours": "8h - 17h",
        "is_free": True,
        "accepts_anonymous": True,
    },
    {
        "name": "Hopital de Bobo-Dioulasso",
        "center_type": "hospital",
        "description": "Hopital regional de Bobo-Dioulasso, deuxieme plus grand du pays.",
        "address": "Quartier Sow, Bobo-Dioulasso",
        "city": "Bobo-Dioulasso",
        "province": "Hauts-Bassins",
        "phone": "+226 20 98 11 63",
        "email": "hopital@bobo.bf",
        "latitude": 11.1771,
        "longitude": -4.2979,
        "services_offered": "Urgences, maternite, gynecologie, chirurgie, pediatrie",
        "opening_hours": "24h/24",
        "is_free": True,
        "accepts_anonymous": True,
    },
    {
        "name": "Hopital de Ouahigouya",
        "center_type": "hospital",
        "description": "Hopital regional de Ouahigouya.",
        "address": "Centre-ville, Ouahigouya",
        "city": "Ouahigouya",
        "province": "Nord",
        "phone": "+226 23 66 00 74",
        "email": "hopital@ouahigouya.bf",
        "latitude": 13.5860,
        "longitude": -2.4114,
        "services_offered": "Urgences, maternite, soins aux victimes de violence",
        "opening_hours": "8h - 17h",
        "is_free": True,
        "accepts_anonymous": True,
    },
    {
        "name": "Commissariat Central de Ouagadougou",
        "center_type": "police",
        "description": "Commissariat central de police de Ouagadougou.",
        "address": "Place de la Republique, Ouagadougou",
        "city": "Ouagadougou",
        "province": "Centre",
        "phone": "+226 25 30 62 82",
        "email": "",
        "latitude": 12.3686,
        "longitude": -1.5147,
        "services_offered": "Depot de plainte, protection des victimes, mediation",
        "opening_hours": "24h/24",
        "is_free": True,
        "accepts_anonymous": True,
    },
    {
        "name": "Commissariat de Bobo-Dioulasso",
        "center_type": "police",
        "description": "Commissariat de police de Bobo-Dioulasso.",
        "address": "Quartier Accart-Ville, Bobo-Dioulasso",
        "city": "Bobo-Dioulasso",
        "province": "Hauts-Bassins",
        "phone": "+226 20 98 23 12",
        "email": "",
        "latitude": 11.1752,
        "longitude": -4.2980,
        "services_offered": "Depot de plainte, protection des victimes",
        "opening_hours": "24h/24",
        "is_free": True,
        "accepts_anonymous": True,
    },
    {
        "name": "Gendarmerie Nationale - Ouagadougou",
        "center_type": "police",
        "description": "Gendarmerie nationale, base principale.",
        "address": "Kossodo, Ouagadougou",
        "city": "Ouagadougou",
        "province": "Centre",
        "phone": "+226 25 41 00 11",
        "email": "",
        "latitude": 12.3820,
        "longitude": -1.4890,
        "services_offered": "Depot de plainte, enquetes, protection",
        "opening_hours": "24h/24",
        "is_free": True,
        "accepts_anonymous": True,
    },
    {
        "name": "Association Burkinabe des Femmes Juristes (ABFJ)",
        "center_type": "legal",
        "description": "Aide juridique aux femmes victimes de violences.",
        "address": "Karpala, Ouagadougou",
        "city": "Ouagadougou",
        "province": "Centre",
        "phone": "+226 25 37 06 23",
        "email": "abfj@abfj.bf",
        "latitude": 12.3550,
        "longitude": -1.5300,
        "services_offered": "Conseil juridique, accompagnement judiciaire, aide aux victimes",
        "opening_hours": "8h - 17h",
        "is_free": True,
        "accepts_anonymous": True,
    },
    {
        "name": "Centre de Mediation Familiale de Ouaga",
        "center_type": "legal",
        "description": "Centre de mediation et de resolution des conflits familiaux.",
        "address": "Patte d'Oie, Ouagadougou",
        "city": "Ouagadougou",
        "province": "Centre",
        "phone": "+226 25 36 45 00",
        "email": "",
        "latitude": 12.3620,
        "longitude": -1.5280,
        "services_offered": "Mediation familiale, conseil juridique, orientation",
        "opening_hours": "8h - 16h30",
        "is_free": True,
        "accepts_anonymous": True,
    },
    {
        "name": "ONG Femmes et Droits Humains (WDH)",
        "center_type": "ngo",
        "description": "Organisation de defense des droits des femmes au Burkina Faso.",
        "address": "Tampouy, Ouagadougou",
        "city": "Ouagadougou",
        "province": "Centre",
        "phone": "+226 25 43 18 55",
        "email": "contact@wdh.bf",
        "latitude": 12.3800,
        "longitude": -1.5430,
        "services_offered": "Accompagnement, plaidoyer, sensibilisation, aide directe",
        "opening_hours": "8h - 17h",
        "is_free": True,
        "accepts_anonymous": True,
    },
    {
        "name": "Association AJESEF",
        "center_type": "ngo",
        "description": "Association des Jeunes et Femmes pour le Developpement.",
        "address": "Somgande, Ouagadougou",
        "city": "Ouagadougou",
        "province": "Centre",
        "phone": "+226 25 38 70 12",
        "email": "ajesef@ajesef.bf",
        "latitude": 12.3670,
        "longitude": -1.5100,
        "services_offered": "Accompagnement des victimes, formation, autonomisation",
        "opening_hours": "8h - 17h",
        "is_free": True,
        "accepts_anonymous": True,
    },
    {
        "name": "Service Social du CHU Yalgado",
        "center_type": "social",
        "description": "Service social hospitalier pour l'accompagnement des victimes.",
        "address": "CHU Yalgado Ouedraogo, Ouagadougou",
        "city": "Ouagadougou",
        "province": "Centre",
        "phone": "+226 25 33 72 47",
        "email": "",
        "latitude": 12.3695,
        "longitude": -1.5248,
        "services_offered": "Accompagnement social, aide aux victimes de violences, orientation",
        "opening_hours": "8h - 16h",
        "is_free": True,
        "accepts_anonymous": True,
    },
    {
        "name": "Service Social de l'Hopital de Bobo",
        "center_type": "social",
        "description": "Service social de l'hopital regional de Bobo-Dioulasso.",
        "address": "Hopital de Bobo-Dioulasso",
        "city": "Bobo-Dioulasso",
        "province": "Hauts-Bassins",
        "phone": "+226 20 98 11 63",
        "email": "",
        "latitude": 11.1770,
        "longitude": -4.2975,
        "services_offered": "Accompagnement social, soutien psychosocial, aide materielle",
        "opening_hours": "8h - 16h",
        "is_free": True,
        "accepts_anonymous": True,
    },
    {
        "name": "Centre Psycho-Social de Ouaga",
        "center_type": "psychological",
        "description": "Centre de soutien psychologique pour victimes de violences.",
        "address": "Wemtenga, Ouagadougou",
        "city": "Ouagadougou",
        "province": "Centre",
        "phone": "+226 25 44 80 30",
        "email": "csp@ouaga.bf",
        "latitude": 12.3900,
        "longitude": -1.5100,
        "services_offered": "Soutien psychologique, therapie individuelle et de groupe",
        "opening_hours": "8h - 18h",
        "is_free": True,
        "accepts_anonymous": True,
    },
    {
        "name": "Centre d'Accueil des Femmes Victimes",
        "center_type": "shelter",
        "description": "Centre d'hebergement temporaire pour femmes et enfants victimes de violences.",
        "address": "Zone du Bois, Ouagadougou",
        "city": "Ouagadougou",
        "province": "Centre",
        "phone": "+226 25 35 10 00",
        "email": "accueil@cafv.bf",
        "latitude": 12.3600,
        "longitude": -1.5050,
        "services_offered": "Hebergement, alimentation, accompagnement, reinseration sociale",
        "opening_hours": "24h/24",
        "is_free": True,
        "accepts_anonymous": True,
    },
    {
        "name": "Foyer de l'ESPOIR - Bobo-Dioulasso",
        "center_type": "shelter",
        "description": "Centre d'hebergement pour victimes de violences a Bobo-Dioulasso.",
        "address": "Quartier Sara, Bobo-Dioulasso",
        "city": "Bobo-Dioulasso",
        "province": "Hauts-Bassins",
        "phone": "+226 20 98 44 00",
        "email": "espoir@bobo.bf",
        "latitude": 11.1850,
        "longitude": -4.2900,
        "services_offered": "Hebergement, accompagnement, soutien psychosocial",
        "opening_hours": "24h/24",
        "is_free": True,
        "accepts_anonymous": True,
    },
    {
        "name": "Hopital de Kaya",
        "center_type": "hospital",
        "description": "Hopital de Kaya, centre sanitaire regional.",
        "address": "Centre-ville, Kaya",
        "city": "Kaya",
        "province": "Centre-Nord",
        "phone": "+226 26 57 00 22",
        "email": "",
        "latitude": 12.8630,
        "longitude": -1.0800,
        "services_offered": "Urgences, maternite, soins aux victimes",
        "opening_hours": "8h - 17h",
        "is_free": True,
        "accepts_anonymous": True,
    },
    {
        "name": "Hopital de Tenkodogo",
        "center_type": "hospital",
        "description": "Hopital regional de Tenkodogo.",
        "address": "Centre-ville, Tenkodogo",
        "city": "Tenkodogo",
        "province": "Centre-Est",
        "phone": "+226 26 66 00 45",
        "email": "",
        "latitude": 11.7740,
        "longitude": -0.3650,
        "services_offered": "Urgences, maternite, gynecologie",
        "opening_hours": "8h - 17h",
        "is_free": True,
        "accepts_anonymous": True,
    },
]


class Command(BaseCommand):
    help = "Seed the database with support centers in Burkina Faso"

    def handle(self, *args, **options):
        count = 0
        for data in CENTERS:
            obj, created = SupportCenter.objects.get_or_create(
                name=data["name"],
                defaults=data,
            )
            if created:
                count += 1
        self.stdout.write(self.style.SUCCESS(f"{count} centres ajoutes. Total: {SupportCenter.objects.count()}"))
