# Generated by Django 5.2.16 on 2026-07-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='tracking_code',
            field=models.CharField(editable=False, max_length=14, unique=True),
        ),
    ]
